=== raphaeldeoliveira/linguagensvariadas/linguagensDeMarcacao/DTD/3conferencia.dtd
<!DOCTYPE conferencia [
    <!ELEMENT conferencia (sessao+)>
    <!ELEMENT sessao (titulo, palestrante+, participante*)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT palestrante (nome, biografia, temas)>
    <!ELEMENT nome (#PCDATA)>
    <!ELEMENT biografia (#PCDATA)>
    <!ELEMENT temas (tema+)>
    <!ELEMENT tema (#PCDATA)>
    <!ELEMENT participante (nome, email?)>
    <!ELEMENT email (#PCDATA)>
    <!ATTLIST sessao
        id ID #REQUIRED
        data CDATA #REQUIRED
        sala CDATA #IMPLIED>
    <!ATTLIST palestrante
        palestrante_id ID #REQUIRED
        adiliacao CDATA #REQUIRED>
    <!ATTLIST participante
        participante_id ID #REQUIRED
        registrado (sim|nao) "nao">
]>

=== raphaeldeoliveira/linguagensvariadas/linguagensDeMarcacao/DTD/3conferenciavalido.xml
<?xml version="1.0"?>
<!DOCTYPE conferencia SYSTEM "3conferencia.dtd" >
<conferencia>
    <sessao id="S001" data="2023-10-15" sala="101">
        <titulo>Inteligencia Artificial na Saude</titulo>
        <palestrante palestrante_id="P001" afiliacao="Universidade X">
            <nome>Dr. Alice Martins</nome>
            <biografia>PhD em IA</biografia>
            <temas>
                <tema>Aplicações de Ia em diagnostico</tema>
            </temas>
        </palestrante>
        <participante participante_id="PT001" registrado="sim">
            <nome>Maria Silva</nome>
            <email>maria.silva@email.com</email>
        </participante>
    </sessao>
</conferencia>
